# src/chat_system.py

import asyncio
import json
import logging
from typing import Dict, Any, Optional, Tuple
from collections import defaultdict
from enum import Enum, auto

from src.database.context_manager import ContextManager
from src.engine import TextEngine
from src.message_handler import BotLogic
from src.persona import Persona
from src.utils.model_utils import get_model_list
from src.utils.save_utils import save_personas_to_file, load_personas_from_file

logger = logging.getLogger(__name__)


class ResponseType(Enum):
    """Enumeration for the type of response generated by the ChatSystem."""
    DEV_COMMAND = auto()
    LLM_GENERATION = auto()


class ChatSystem:
    def __init__(self, context_manager: ContextManager, text_engine: TextEngine) -> None:
        self.personas: Dict[str, Persona] = load_personas_from_file()
        self.context_manager: ContextManager = context_manager
        self.text_engine: TextEngine = text_engine
        self.bot_logic: BotLogic = BotLogic(self)
        self.last_api_requests: Dict[str, Dict[str, Optional[Dict[str, Any]]]] = defaultdict(dict)
        self.models_available: Dict[str, Any] = get_model_list()
        self.background_tasks = set()

    async def _guess_and_record_business(self, contact_id: int, user_identifier: str) -> None:
        try:
            logger.info(f"Performing business affiliation guess for new contact ID {contact_id}.")
            businesses = self.context_manager.get_all_businesses()
            if not businesses: return
            business_list_str = ", ".join([f"'{b['business_name']}' (ID: {b['business_id']})" for b in businesses])
            classifier_persona = self.personas.get('derpr') or next(iter(self.personas.values()))
            prompt = (
                f"Analyze user identifier '{user_identifier}'. Which business is the most likely match: {business_list_str}? Respond: `ID: <id>, Reason: <reasoning>`. If none, `ID: None, Reason: <reasoning>`.")
            context_object = {"persona_prompt": prompt, "history": [], "current_message": {"text": ""}}

            raw_guess, _ = await self.text_engine.generate_response(
                classifier_persona.get_config_for_engine(),
                context_object
            )

            guessed_id_str = raw_guess.split("ID:")[1].split(",")[0].strip()
            reasoning = raw_guess.split("Reason:")[1].strip()
            guessed_id = int(guessed_id_str) if guessed_id_str.lower() != 'none' else None

            self.context_manager.record_business_guess(contact_id, guessed_id, reasoning)
            logger.info(f"Recorded business guess for contact {contact_id}: Business ID {guessed_id}")
        except Exception as e:
            logger.error(f"Failed to guess business for contact {contact_id}: {e}", exc_info=True)

    async def generate_response(
            self,
            persona_name: str,
            user_identifier: str,
            channel: str,
            message: str,
            image_url: Optional[str] = None,
            history_limit: Optional[int] = None
    ) -> Tuple[str, ResponseType]:
        """Orchestrates response generation, returning the response string and its type."""
        command_result = await self.bot_logic.preprocess_message(persona_name, user_identifier, message)
        if command_result:
            if command_result.get("mutated", False):
                save_personas_to_file(self.personas)
            return command_result["response"], ResponseType.DEV_COMMAND

        try:
            persona = self.personas.get(persona_name)
            if not persona:
                logger.error(f"Persona '{persona_name}' does not exist.")
                return "Error: Persona not found.", ResponseType.DEV_COMMAND

            contact_id, ticket_id, is_new_contact = self.context_manager.get_context_for_generation(user_identifier,
                                                                                                    channel)
            if is_new_contact:
                task = asyncio.create_task(self._guess_and_record_business(contact_id, user_identifier))
                self.background_tasks.add(task)
                task.add_done_callback(self.background_tasks.discard)

            self.context_manager.log_interaction(ticket_id, 'inbound', message, channel, image_url)

            # Determine the effective history limit. Prioritize the persona's setting.
            effective_limit = persona.get_context_length()
            if effective_limit is None:
                effective_limit = history_limit  # Fallback to the limit from the interface call

            context_object = self.context_manager.build_prompt_context_object(contact_id, effective_limit)
            context_object["persona_prompt"] = persona.get_prompt()
            context_object["current_message"] = {"text": message, "image_url": image_url}

            persona_config = persona.get_config_for_engine()
            reply_content, api_payload = await self.text_engine.generate_response(persona_config, context_object)

            self.last_api_requests[user_identifier][persona_name] = api_payload

            self.context_manager.log_interaction(ticket_id, 'outbound', reply_content, channel)
            return reply_content, ResponseType.LLM_GENERATION

        except Exception as e:
            logger.error(f"Error in generate_response for {user_identifier}: {e}", exc_info=True)
            return "An internal error occurred while processing your request.", ResponseType.DEV_COMMAND
