# src/chat_system.py

import asyncio
import json
import logging
import re
from typing import Dict, Any, Optional, Tuple
from collections import defaultdict
from enum import Enum, auto
from urllib.parse import urlparse

from src.database.memory_manager import MemoryManager
from src.clients.zammad_client import ZammadClient
from config.global_config import SUPPORT_CHANNELS
from src.engine import TextEngine
from src.message_handler import BotLogic
from src.persona import Persona
from src.utils.model_utils import get_model_list
from src.utils.save_utils import save_personas_to_file, load_personas_from_file

logger = logging.getLogger(__name__)


class ResponseType(Enum):
    """Enumeration for the type of response generated by the ChatSystem."""
    DEV_COMMAND = auto()
    LLM_GENERATION = auto()


class ChatSystem:
    def __init__(self, memory_manager: MemoryManager, text_engine: TextEngine, zammad_client: ZammadClient) -> None:
        self.personas: Dict[str, Persona] = load_personas_from_file()
        self.memory_manager: MemoryManager = memory_manager
        self.text_engine: TextEngine = text_engine
        self.zammad_client: ZammadClient = zammad_client
        self.bot_logic: BotLogic = BotLogic(self)
        self.last_api_requests: Dict[str, Dict[str, Optional[Dict[str, Any]]]] = defaultdict(dict)
        self.models_available: Dict[str, Any] = get_model_list()
        self.background_tasks = set()

    def _should_create_ticket(self, channel: str, message: str) -> bool:
        """Determines if an interaction should generate a Zammad ticket."""
        return channel.lower() in [c.lower() for c in SUPPORT_CHANNELS]

    def _find_ticket_id_in_message(self, message: str) -> Optional[int]:
        """Finds a ticket ID pattern like [Ticket#12345] in a message."""
        match = re.search(r'\[Ticket#(\d+)\]', message, re.IGNORECASE)
        if match:
            return int(match.group(1))
        return None

    async def _get_or_create_zammad_user(self, user_identifier: str, channel: str) -> Optional[int]:
        """
        Finds a Zammad user by email or creates a new one. Handles non-email identifiers
        by creating a unique, channel-specific dummy email. Returns the Zammad user ID.
        """
        email_match = re.search(r'<(.+?)>', user_identifier)
        is_real_email = email_match is not None

        if is_real_email:
            email = email_match.group(1)
            name_part = user_identifier.split('<')[0].strip()
            name_parts = name_part.split()
            firstname = name_parts[0] if name_parts else "Unknown"
            lastname = ' '.join(name_parts[1:]) if len(name_parts) > 1 else "User"
            note = None
        else:
            domain = urlparse(self.zammad_client.api_url).hostname
            email = f"{channel.lower()}-{user_identifier}@{domain}"
            firstname = f"{channel.capitalize()} User"
            lastname = user_identifier
            note = f"Auto-generated user from {channel.capitalize()}. Original identifier: {user_identifier}"

        try:
            search_results = await asyncio.to_thread(self.zammad_client.search_user, email)
            if search_results:
                return search_results[0]['id']

            logger.info(f"Creating new Zammad user for identifier '{user_identifier}' with email: {email}")
            new_user = await asyncio.to_thread(
                self.zammad_client.create_user,
                email=email, firstname=firstname, lastname=lastname, note=note
            )
            return new_user['id']

        except Exception as e:
            logger.error(f"Error getting or creating Zammad user for '{user_identifier}': {e}", exc_info=True)
            return None

    async def generate_response(
            self,
            persona_name: str,
            user_identifier: str,
            channel: str,
            message: str,
            image_url: Optional[str] = None,
            history_limit: Optional[int] = None
    ) -> Tuple[str, ResponseType]:
        """Orchestrates response generation, returning the response string and its type."""
        command_result = await self.bot_logic.preprocess_message(persona_name, user_identifier, message)
        if command_result:
            if command_result.get("mutated", False):
                save_personas_to_file(self.personas)
            return command_result["response"], ResponseType.DEV_COMMAND

        ticket_to_log = None # Initialize here to be available in the final except block
        try:
            persona = self.personas.get(persona_name)
            if not persona:
                return "Error: Persona not found.", ResponseType.DEV_COMMAND

            effective_limit = persona.get_context_length() if persona.get_context_length() is not None else history_limit
            history_from_db = self.memory_manager.get_history(user_identifier, effective_limit)
            interaction_history = []
            for item in history_from_db:
                interaction_history.append({"role": "user", "content": item["user_message"]})
                interaction_history.append({"role": "assistant", "content": item["bot_response"]})

            context_object = {"persona_prompt": persona.get_prompt(), "history": interaction_history, "current_message": {"text": message, "image_url": image_url}}
            is_ticket_request = self._should_create_ticket(channel, message)
            zammad_ticket_id = self._find_ticket_id_in_message(message)

            if is_ticket_request:
                # This inner block isolates Zammad errors, ensuring the interaction is logged even if Zammad fails.
                try:
                    customer_id = await self._get_or_create_zammad_user(user_identifier, channel)
                    if customer_id:
                        if zammad_ticket_id:
                            await asyncio.to_thread(self.zammad_client.add_article_to_ticket, ticket_id=zammad_ticket_id, body=message)
                            ticket_to_log = zammad_ticket_id
                        else:
                            sanitized_identifier = user_identifier.split('<')[0].strip()
                            title = f"New request from {sanitized_identifier} via {channel}"
                            new_ticket = await asyncio.to_thread(self.zammad_client.create_ticket, title=title, group='Users', customer_id=customer_id, article_body=message)
                            ticket_to_log = new_ticket.get('id') if new_ticket else None
                except Exception as zammad_error:
                    logger.error(f"A Zammad API error occurred during ticket creation: {zammad_error}", exc_info=True)

            reply_content, api_payload = await self.text_engine.generate_response(persona.get_config_for_engine(), context_object)
            self.last_api_requests[user_identifier][persona_name] = api_payload

            self.memory_manager.log_interaction(
                user_identifier=user_identifier, channel=channel, user_message=message,
                bot_response=reply_content, zammad_ticket_id=ticket_to_log
            )

            if is_ticket_request and ticket_to_log:
                try:
                    await asyncio.to_thread(self.zammad_client.add_article_to_ticket, ticket_id=ticket_to_log, body=reply_content)
                except Exception as e:
                    logger.error(f"Failed to add bot reply to Zammad ticket #{ticket_to_log}. The interaction is still logged locally. Error: {e}", exc_info=True)

            return reply_content, ResponseType.LLM_GENERATION

        except Exception as e:
            # This is the production safety net. It catches any unexpected errors (e.g., from the LLM)
            # and ensures the failed attempt is still logged for auditing.
            logger.error(f"A critical error occurred in generate_response for {user_identifier}: {e}", exc_info=True)
            error_message = f"An internal error occurred: {type(e).__name__}"
            self.memory_manager.log_interaction(
                user_identifier=user_identifier, channel=channel, user_message=message,
                bot_response=error_message, zammad_ticket_id=ticket_to_log
            )
            return "An internal error occurred while processing your request.", ResponseType.DEV_COMMAND
